version: '3.8'

services:
  mono-map-api:
    image: gustavr12/mono-map-api:latest
    build: .
    container_name: mono-map-api
    ports:
      - "3001:3001"
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
      - MAIL_SERVICE=${MAIL_SERVICE}
      - MAIL_SECRET_KEY=${MAIL_SECRET_KEY}
      - MAIL_USER=${MAIL_USER}
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongoMonoApi
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: monoapi
    ports:
      - "27017:27017"
    volumes:
      - mongodb_api_volume:/data/db

volumes:
  mongodb_api_volume: